In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
df = pd.read_csv(r"F:\Self Learning\Code_basics_projects\Customer Churn Dataset\ChurnData.csv")
df.head(4)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,tollmon,equipmon,cardmon,wiremon,longten,tollten,cardten,voice,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,20.75,0.0,15.25,35.7,42.00,211.45,125.0,1.0,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,0.00,0.0,0.00,0.0,288.80,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,0.00,0.0,0.00,0.0,157.05,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,45.00,50.1,23.25,64.9,239.55,1873.05,880.0,1.0,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0

In [31]:
pd.set_option("display.max_columns", None)

In [32]:
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,tollmon,equipmon,cardmon,wiremon,longten,tollten,cardten,voice,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,20.75,0.0,15.25,35.7,42.00,211.45,125.0,1.0,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,0.00,0.0,0.00,0.0,288.80,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,0.00,0.0,0.00,0.0,157.05,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,45.00,50.1,23.25,64.9,239.55,1873.05,880.0,1.0,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,22.00,0.0,23.75,0.0,47.45,166.10,145.0,1.0,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

In [33]:
x = df.drop("churn", axis=1)
Y = df["churn"]

In [34]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [35]:
x = scale.fit_transform(x)

In [36]:
x

array([[-1.13518441, -0.62595491, -0.4588971 , ..., -0.69987184,
         1.28150384,  1.41630855],
       [-0.11604313, -0.62595491,  0.03454064, ...,  0.03858151,
        -0.60481397, -1.36987221],
       [-0.57928917, -0.85594447, -0.261522  , ...,  0.03858151,
        -0.73269992,  0.48758163],
       ...,
       [-1.36680743, -0.7026181 , -0.16283445, ..., -0.21827183,
        -0.13456666,  0.48758163],
       [-0.53296457, -0.85594447, -1.14970993, ...,  2.27177859,
        -0.97515038,  1.41630855],
       [ 1.18104577,  0.67731925,  0.42929083, ...,  0.03858151,
         1.72644039, -0.44114529]])

In [40]:
Y

0      1.0
1      1.0
2      0.0
3      0.0
4      0.0
      ...
195    0.0
196    0.0
197    0.0
198    1.0
199    0.0
Name: churn, Length: 200, dtype: float64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, Y, test_size=.30, random_state=42)

In [41]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((140, 27), (60, 27), (140,), (60,))

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [42]:
pipe = Pipeline([
                ("KNN", KNeighborsClassifier()),   
                ("naive bayes", GaussianNB()),
                ("SVM", SVC()),
                ("Decission Tree", DecisionTreeClassifier()),
                ("Random Forest", RandomForestClassifier())
                ])

for name, model in pipe.steps:
    model.fit(X_train, Y_train)
    y_hat = model.predict(X_test)
    score = accuracy_score(Y_test, y_hat)
    report = classification_report(Y_test, y_hat)
    print("The accuracy of the model {} is: {}:".format(name, score))
    print(report)

The accuracy of the model KNN is: 0.6833333333333333:
              precision    recall  f1-score   support

         0.0       0.84      0.71      0.77        45
         1.0       0.41      0.60      0.49        15

    accuracy                           0.68        60
   macro avg       0.63      0.66      0.63        60
weighted avg       0.73      0.68      0.70        60

The accuracy of the model naive bayes is: 0.7333333333333333:
              precision    recall  f1-score   support

         0.0       0.91      0.71      0.80        45
         1.0       0.48      0.80      0.60        15

    accuracy                           0.73        60
   macro avg       0.70      0.76      0.70        60
weighted avg       0.81      0.73      0.75        60

The accuracy of the model SVM is: 0.7666666666666667:
              precision    recall  f1-score   support

         0.0       0.84      0.84      0.84        45
         1.0       0.53      0.53      0.53        15

    accuracy                           0.77        60
   macro avg       0.69      0.69      0.69        60
weighted avg       0.77      0.77      0.77        60

The accuracy of the model Decission Tree is: 0.7:
              precision    recall  f1-score   support

         0.0       0.81      0.78      0.80        45
         1.0       0.41      0.47      0.44        15

    accuracy                           0.70        60
   macro avg       0.61      0.62      0.62        60
weighted avg       0.71      0.70      0.71        60

The accuracy of the model Random Forest is: 0.8:
              precision    recall  f1-score   support

         0.0       0.88      0.84      0.86        45
         1.0       0.59      0.67      0.62        15

    accuracy                           0.80        60
   macro avg       0.74      0.76      0.74        60
weighted avg       0.81      0.80      0.80        60